#define CMDCODE_SHOW_NW_TOPOLOGY 1 /*show topology*/
#define CMDCODE_RUN_RESOLVE_ARP 2 /*run arp handler*/
#define CMDCODE_RUN_PING 9
#define CMDCODE_RUN_SPF 12
#define CMDCODE_RUN_SPF_ALL 14
#define CMDCODE_RUN_SOLICIT 15

#define CMDCODE_SHOW_ARP_TABLE 3
#define CMDCODE_SHOW_MAC_TABLE 4
#define CMDCODE_SHOW_ROUTE_TABLE 5
#define CMDCODE_SHOW_SPF 13


#define CMDCODE_CONFIG_DEFAULT_GW 6
#define CMDCODE_CONFIG_L3_TABLE 7
#define CMDCODE_CONFIG_SVI 8
#define CMDCODE_CONFIG_UP 10
#define CMDCODE_CONFIG_COST_METRIC 15
#define CMDCODE_SHOW_INTF_STAT 11
